version: "3.9"
services:
  web:
    build: .
    expose:
      - "5000"
  mitmproxy:
    image: mitmproxy/mitmproxy
    command: "mitmweb --web-host 0.0.0.0 --mode reverse:http://web:5000/"
    ports: 
      - "80:8080"
      - "127.0.0.1:8081:8081"
    depends_on:
      - web